###### FSBank Configuration ######

# sql settings
sql-conf:
    host: http://localhost:3306
    service-key: xxxxxxxxxxxxxxxxx

# bank currency settings
bank-conf:
    name: "FSBank"

currency-conf:
    default-balance: 1000.00
    name: "FP"
    plural: "FP"
    format: "{major}.{minor}{plural}"

config-version: 2